import type { TopoGraph } from "../topology-graph.js";
import { cardClass } from "./card-variants.js";

// The map's visual vocabulary, stated on the page that uses it. It moved here from `views.ts`
// when the map's styling moved to Tailwind, and the move is what KEEPS the rule it has always
// had rather than breaking it.
//
// That rule: a swatch must be the same element with the same classes as the thing it explains.
// It is not pedantry — it drifted once, when the worker mark was the border of a CARD and the
// legend drew it as a line, so the two came out different colours at equal specificity. A
// server-rendered legend would now have to hand-copy Tailwind class strings out of `nodes.tsx`,
// which is that same failure with more steps. Here it calls `cardClass()` — the one function
// the cards themselves call — so a restyle cannot leave the key behind.
//
// Conditional on what was actually drawn: a key explaining a mark that is not on screen is a
// key that has to be read past.
export function Legend({ graph }: { graph: TopoGraph }): React.JSX.Element {
  const unconfigured = graph.nodes.some((n) => !n.data.configured);
  const viaWorker = graph.nodes.some((n) => n.data.viaWorker);

  // Size and padding are the ONLY overrides, and they go THROUGH cardClass rather than being
  // concatenated after it. That is the difference between a swatch and a bug: cn's twMerge
  // drops the conflicting base (w-full, h-full), so one width ships. Concatenating leaves both
  // and lets source order decide — and no important modifier fixes it, because the v3 prefix
  // form is not generated by Tailwind v4 at all and the v4 suffix form makes twMerge keep BOTH.
  // Plain overrides, passed in last, is the only form that works. There is a test.
  const SWATCH = "w-[22px] h-3.5 p-0 rounded-[3px] shrink-0";
  const key = (className: string, text: string) => (
    <li className="flex items-center gap-2 min-w-0">
      <div className={className} aria-hidden="true" />
      {text}
    </li>
  );

  return (
    <ul className="list-none m-0 px-4 pt-3 pb-4 border-t border-[var(--border)] flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-muted-foreground">
      {key(cardClass({ kind: "agent", className: SWATCH }), "this agent")}
      {viaWorker ? key(cardClass({ kind: "backend", viaWorker: true, className: SWATCH }), "reached over SQS via llm-worker") : null}
      {unconfigured ? key(cardClass({ kind: "outbound", off: true, className: SWATCH }), "not configured") : null}
      {/* React Flow's <Controls> gives zoom and fit buttons but names no gestures, and none of
          these is discoverable: the wheel is deliberately not captured (see zoomOnScroll in
          topology.tsx — a map that swallows the scroll traps a reader trying to reach the
          tables below it), a card can be moved, and a card with a + opens. */}
      <li className="ml-auto italic max-[46rem]:ml-0">
        Drag to move · Ctrl + scroll to zoom · <b>+</b> opens a card · ↓ jumps to its row below.
      </li>
    </ul>
  );
}
